### ISSUE TITLE
Where create the functions

### ISSUE THREAD

**Issue by Mairafatoretto** [Gabriel382/multi-objective-optimization-algorithms#1]
Hello, i dont understand where are you creating the functions.

**Comment by Gabriel382** [comment]
Hi, you can find the functions on https://github.com/Gabriel382/multi-objective-optimization-algorithms/tree/master/pyCodes

**Comment by Mairafatoretto** [comment]
In which file?

**Comment by Gabriel382** [comment]
I'm really sorry for the late answer, I hope you could find the right file that you were searching. Each file in the [pyCodes](https://github.com/Gabriel382/multi-objective-optimization-algorithms/tree/master/pyCodes) had a function for each optimization algorithm.
